### ISSUE TITLE
Redirect user if on nonexistent page

### ISSUE THREAD

**Issue by armaangoel78** [CHSCodeForChange/Sapphire-web#28]
Whenever you go to a page that doesn't exist, it currently just gives you an error. We should really make it so that users are redirected, either to a page that does exist (like if you try to view a slot that doesn't exist you are brought to the slotNeeds page) or to a customized 404 page so it looks not terrible

**Comment by jpaav** [comment]
I've fixed this and added the necessary resources and code. In order to see the 404 and 500 error pages, you have to go into settings and set DEBUG=True and ALLOWED_HOSTS to the commented out version. This is because you can either have the error messages for errors or 404 pages, not both. When we set up the production server, it will render the 404 pages.
